server:
  error:
    path: /error
  address: 172.20.178.150
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: gomoku-online
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources
logging:
  level:
    root: info
  pattern:
    console: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n