server:
  error:
    path: /error
  address: localhost
  port: 8080
  servlet:
    context-path: /api
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
