server:
  error:
    path: /error
  address: localhost
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: gomoku-online
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources
logging:
  level:
    root: debug
